# Makefile for NueAna XTalkFilter

# Run rootcint

#ROOTCINTFLAGS := -p
ROOTCINT:=YES


PACKAGE:=XTalkFilter
LIB:=lib$(PACKAGE)

# library contents

LIBCXXFILES:=$(wildcard *.cxx)

############

include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk




