# Makefile for NueAna Reweight

# Run rootcint

#ROOTCINT:=NO
ROOTCINT:=YES

#LIB:=lib$(PACKAGE)Reweight

PACKAGE:=NueAnaReweight
LIB:=lib$(PACKAGE)
# library contents

LIBCXXFILES:=$(wildcard *.cxx)


############

include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk

