#
# GNUmakefile for simple package
#



ROOTCINT := YES

PACKAGE := NueAnaParticleAnaTools


LIB := lib$(PACKAGE)
LIBCXXFILES := $(wildcard *.cxx)
########################################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
#


