#
# GNUmakefile for simple package
#

SUBDIRS = Display Managed Systematic
#SUBDIRS = Reporter  Truth Display

PACKAGE := NueAnaParticleFinder

ROOTCINT := YES
LIB := lib$(PACKAGE)
LIBCXXFILES := $(wildcard *.cxx)
########################################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
#


