# Makefile for NueAna/MultiBinAna package

# Define whether rootcint should be run to generate ROOT dictionaries
ROOTCINT = YES

# library 
PACKAGE:=NueAnaMultiBinAna
LIB := lib$(PACKAGE)

#library contents
LIBCXXFILES := $(wildcard *.cxx)

########################################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk

