#
# GNUmakefile for simple package
#

#SUBDIRS = 



PACKAGE := NueAnaParticleSystematic
ROOTCINT := YES
LIB := lib$(PACKAGE)
LIBCXXFILES := $(wildcard *.cxx)
########################################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
#


