#
# GNUmakefile for simple package
#

SUBDIRS = 

ROOTCINT := YES
PACKAGE := NueAnaParticlePlotter
LIB := lib$(PACKAGE)
LIBCXXFILES := $(wildcard *.cxx)
########################################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
#


