# Makefile for NueAna Display

# Run rootcint

#ROOTCINTFLAGS := -p
ROOTCINT:=YES

#LIB:=lib$(PACKAGE)Display
PACKAGE:=NueAnaDisplay
LIB:=lib$(PACKAGE)

# library contents

LIBCXXFILES:=$(wildcard *.cxx)

############

include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
include SoftRelTools/arch_spec_sigc++.mk



