#
# GNUmakefile for simple package
#



ROOTCINT := YES
#LIB := lib$(PACKAGE)
PACKAGE := NueAnaParticleManaged
LIB := lib$(PACKAGE)
LIBCXXFILES := $(wildcard *.cxx)
########################################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
#


