#
# GNUmakefile for simple package
#

SUBDIRS = ParticleFinder ParticleAna Analysis

ROOTCINT := YES

PACKAGE := NueAnaParticlePID

LIB := lib$(PACKAGE)

LIBCXXFILES := $(wildcard *.cxx)
########################################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
#


